
# .github/workflows/workflow.yml
name: Streamlit app

on:
  workflow_dispatch:
    branches: ["master"]

  push:
    branches: ["master"]

concurrency:
  group: "pages"
  cancel-in-progress: true
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  issues: write

jobs:
  streamlit:
    runs-on: ubuntu-latest
    env:
      PATH_PREFIX: /${{github.event.repository.name}}/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: streamlit_app.py
          ruff: true
      # Setup pages
      - name: Configure pages
        uses: actions/configure-pages@v4
      # Use GitHub Actions artifacts to upload a zip file
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: streamlit
    runs-on: ubuntu-latest

    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

